#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Travis Sparks
"""Silent git automation for QRALPH pipeline."""

from __future__ import annotations

import re
import subprocess
from typing import Tuple


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _sanitize_branch_name(name: str) -> str:
    """Replace non-alphanumeric chars (except /, -, _) with dashes, collapse multiples."""
    result = re.sub(r"[^a-zA-Z0-9/_\-]", "-", name)
    result = re.sub(r"-{2,}", "-", result)
    result = result.strip("-")
    return result


def _run_git(args: list[str], cwd: str, timeout: int = 30) -> Tuple[int, str]:
    """Run a git subprocess with shell=False. Returns (returncode, output)."""
    try:
        proc = subprocess.run(
            ["git"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout,
            shell=False,
        )
        output = proc.stdout + proc.stderr
        return (proc.returncode, output)
    except FileNotFoundError as exc:
        return (-1, f"FileNotFoundError: {exc}")
    except subprocess.TimeoutExpired:
        return (-1, f"Timeout expired after {timeout}s")


def _run_gh(args: list[str], cwd: str, timeout: int = 60) -> Tuple[int, str]:
    """Run a gh CLI subprocess with shell=False. Returns (returncode, output)."""
    try:
        proc = subprocess.run(
            ["gh"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout,
            shell=False,
        )
        output = proc.stdout + proc.stderr
        return (proc.returncode, output)
    except FileNotFoundError:
        raise
    except subprocess.TimeoutExpired:
        return (-1, f"Timeout expired after {timeout}s")


# ─── Public API ──────────────────────────────────────────────────────────────


def is_git_repo(cwd: str) -> bool:
    """Check if cwd is inside a git work tree."""
    rc, _ = _run_git(["rev-parse", "--is-inside-work-tree"], cwd=cwd)
    return rc == 0


def get_default_branch(cwd: str) -> str:
    """Detect the default branch name (main or master)."""
    rc, out = _run_git(["symbolic-ref", "refs/remotes/origin/HEAD"], cwd=cwd)
    if rc == 0 and out.strip():
        return out.strip().split("/")[-1]

    rc, _ = _run_git(["rev-parse", "--verify", "main"], cwd=cwd)
    if rc == 0:
        return "main"

    return "master"


def create_branch(project_id: str, cwd: str) -> dict:
    """Create or switch to qralph/<sanitized-project-id> branch."""
    sanitized = _sanitize_branch_name(project_id)
    branch = f"qralph/{sanitized}"

    rc, _ = _run_git(["rev-parse", "--verify", branch], cwd=cwd)
    if rc == 0:
        rc, out = _run_git(["checkout", branch], cwd=cwd)
        if rc != 0:
            return {"success": False, "branch": branch, "error": out.strip()}
        return {"success": True, "branch": branch, "error": ""}

    rc, out = _run_git(["checkout", "-b", branch], cwd=cwd)
    if rc != 0:
        return {"success": False, "branch": branch, "error": out.strip()}
    return {"success": True, "branch": branch, "error": ""}


def commit_changes(target_dir: str, message: str, cwd: str) -> dict:
    """Stage files in target_dir and commit if anything changed."""
    rc, out = _run_git(["add", target_dir], cwd=cwd)
    if rc != 0:
        return {"success": False, "committed": False, "error": out.strip()}

    rc, _ = _run_git(["diff", "--cached", "--quiet"], cwd=cwd)
    if rc == 0:
        return {"success": True, "committed": False, "error": ""}

    rc, out = _run_git(
        ["-c", "user.name=QRALPH", "-c", "user.email=qralph@pipeline",
         "commit", "-m", message],
        cwd=cwd,
    )
    if rc != 0:
        return {"success": False, "committed": False, "error": out.strip()}
    return {"success": True, "committed": True, "error": ""}


def push_and_create_pr(
    branch: str,
    project_id: str,
    request: str,
    cwd: str,
    version: str = "",
) -> dict:
    """Push branch and create a PR via gh CLI."""
    result = {"success": False, "pr_url": "", "error": "", "message": ""}

    # Step 1: Push
    rc, out = _run_git(["push", "-u", "origin", branch], cwd=cwd)
    if rc != 0:
        result["error"] = out.strip()
        return result

    # Step 2: Build PR metadata
    body_parts = [f"## QRALPH Project: {project_id}\n"]
    if version:
        body_parts.append(f"**Pipeline version:** {version}\n")
    body_parts.append(f"**Request:** {request}\n")
    body_parts.append("\n---\nGenerated by QRALPH pipeline.")
    body = "\n".join(body_parts)

    title = f"qralph({project_id}): {request[:60]}"

    # Step 3: Create PR via gh
    try:
        rc, out = _run_gh(
            ["pr", "create", "--title", title, "--body", body],
            cwd=cwd,
        )
        if rc == 0:
            result["success"] = True
            result["pr_url"] = out.strip()
            return result

        # PR might already exist
        if "already exists" in out.lower():
            try:
                rc2, out2 = _run_gh(
                    ["pr", "view", "--json", "url", "-q", ".url"],
                    cwd=cwd,
                    timeout=30,
                )
                if rc2 == 0:
                    result["success"] = True
                    result["pr_url"] = out2.strip()
                    result["message"] = "PR already existed"
                    return result
            except FileNotFoundError:
                pass

        result["error"] = out.strip()
        return result

    except FileNotFoundError:
        result["success"] = True
        result["message"] = "Branch pushed. Create PR manually (gh CLI not installed)."
        return result
